import { Post } from '../types';

export const SAMPLE_POSTS: Post[] = [
  {
    id: 'sample-1',
    source: 'sample',
    sourceUrl: 'https://www.facebook.com/NASA/posts/pfbid02zEwJ8YpT1L4K9v7',
    author: 'NASA - National Aeronautics and Space Administration',
    authorHandle: '@NASA',
    authorProfileUrl: 'https://www.facebook.com/NASA',
    authorAvatarUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=150&auto=format&fit=crop&q=80',
    verified: true,
    badgeType: 'blue',
    text: `✨ Deep field wonder: Thousands of galaxies, each containing billions of stars, captured in breathtaking high definition.

"Somewhere, something incredible is waiting to be known." When we look back at the earliest cosmic structures, we are peering through time itself. What will the next generation discover? 🚀🌌`,
    images: [
      {
        id: 'img-1',
        url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80',
        width: 1200,
        height: 800,
        alt: 'Deep space cosmic nebula with stars',
      },
    ],
    publishedAt: 'October 14, 2025 at 3:45 PM',
    reactions: 142800,
    topReactions: ['love', 'wow', 'like'],
    comments: 8940,
    shares: 24500,
    engagementTotal: 176240,
    location: 'Houston, Texas',
    privacy: 'public',
  },
  {
    id: 'sample-2',
    source: 'sample',
    sourceUrl: 'https://www.facebook.com/TechCrunch/posts/pfbid039XyQZ4k9v7',
    author: 'TechCrunch',
    authorHandle: '@techcrunch',
    authorProfileUrl: 'https://www.facebook.com/TechCrunch',
    authorAvatarUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    verified: true,
    badgeType: 'blue',
    text: `⚡ BREAKING: Open-weights multimodal models achieve new state-of-the-art benchmarks in real-time visual reasoning and zero-shot robotic task planning. 

Industry analysts predict widespread adoption across autonomous logistics, medical diagnostic imaging, and personalized education within the next 18 months.`,
    images: [
      {
        id: 'img-tc-1',
        url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=900&auto=format&fit=crop&q=80',
        width: 900,
        height: 600,
        alt: 'Neural network AI visualizer',
      },
      {
        id: 'img-tc-2',
        url: 'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=900&auto=format&fit=crop&q=80',
        width: 900,
        height: 600,
        alt: 'Modern workspace technology',
      },
      {
        id: 'img-tc-3',
        url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=900&auto=format&fit=crop&q=80',
        width: 900,
        height: 600,
        alt: 'Futuristic code and data streams',
      },
    ],
    publishedAt: 'Yesterday at 9:15 AM',
    reactions: 18450,
    topReactions: ['like', 'love', 'care'],
    comments: 1320,
    shares: 4210,
    engagementTotal: 23980,
    privacy: 'public',
  },
  {
    id: 'sample-3',
    source: 'sample',
    sourceUrl: 'https://www.facebook.com/markzuckerberg/posts/pfbid041LpQ',
    author: 'Mark Zuckerberg',
    authorHandle: '@zuck',
    authorProfileUrl: 'https://www.facebook.com/zuck',
    authorAvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    verified: true,
    badgeType: 'blue',
    text: `Building technology that brings people together and connects the world has always been our mission. Excited to share our new advancements in holographic displays and neural wristbands. Can't wait for everyone to experience it!`,
    images: [],
    publishedAt: '2 hrs ago',
    reactions: 68900,
    topReactions: ['like', 'love', 'haha'],
    comments: 9400,
    shares: 11200,
    engagementTotal: 89500,
    privacy: 'public',
  },
  {
    id: 'sample-4',
    source: 'sample',
    sourceUrl: 'https://www.facebook.com/NationalGeographic/posts/pfbid052KvR',
    author: 'National Geographic',
    authorHandle: '@natgeo',
    authorProfileUrl: 'https://www.facebook.com/natgeo',
    authorAvatarUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=150&auto=format&fit=crop&q=80',
    verified: true,
    badgeType: 'blue',
    text: `🌿 Beneath the ancient canopy of the Pacific Northwest, life thrives in the delicate microclimates of old-growth mosses. 

Photographer @sarah_lynch spent three weeks documenting the hidden fungal networks that sustain entire redwood forests through chemical signaling. 

Photo by Sarah Lynch / National Geographic Expeditions.`,
    images: [
      {
        id: 'natgeo-1',
        url: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=1000&auto=format&fit=crop&q=80',
        width: 1000,
        height: 750,
        alt: 'Sunbeams penetrating misty forest canopy',
      },
      {
        id: 'natgeo-2',
        url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1000&auto=format&fit=crop&q=80',
        width: 1000,
        height: 750,
        alt: 'Deep emerald pine forest',
      },
      {
        id: 'natgeo-3',
        url: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=1000&auto=format&fit=crop&q=80',
        width: 1000,
        height: 750,
        alt: 'Macro photograph of forest moss and droplets',
      },
      {
        id: 'natgeo-4',
        url: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=1000&auto=format&fit=crop&q=80',
        width: 1000,
        height: 750,
        alt: 'Lush autumn woodland',
      },
    ],
    publishedAt: '3 days ago · 🌍 Public',
    reactions: 95400,
    topReactions: ['love', 'wow', 'care'],
    comments: 3120,
    shares: 18700,
    engagementTotal: 117220,
    location: 'Olympic National Park, Washington',
    privacy: 'public',
  },
];
